blog_demo:
    resource: "@BlogDemoBundle/Resources/config/routing.yml"
    prefix:   /blog

#ouisend_admin:
#    resource: "@OuisendAdminBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
