<?php

namespace OuisendAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommunicationTrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationTrackingRepository extends EntityRepository
{
}
