<?php

namespace OuisendAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PackageSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageSizeRepository extends EntityRepository
{
}
