<?php

namespace OuisendAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransportationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportationTypeRepository extends EntityRepository
{
}
